#!/bin/bash
git config --global alias.a "add -p"
git config --global alias.c "commit"
git config --global alias.s "status"
git config --global alias.ps "push"
git config --global alias.pl "pull --autostash --rebase"
git config --global alias.co "checkout"
git config --global alias.b "checkout -b"
git config --global alias.d "diff --color-words"
git config --global alias.dc "diff --color-words --cached"
git config --global alias.dn "diff --color-words --cached --name-only"
git config --global alias.l "log --oneline --graph --decorate --all"
git config --global alias.cp "cherry-pick"
git config --global alias.mt "mergetool"
git config --global alias.rc "rebase --continue"
git config --global alias.pristine "reset --hard && git clean -dfx"


git config --global alias.st "stash"
git config --global alias.sp "stash pop"
git config --global alias.pu "--set-upstream origin $(git rev-parse --abbrev-ref HEAD)"
